// <auto-generated />
using System;
using CodeFirstDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstDemo.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20211221053825_CodeFirstDemo.Models.EmployeeContextseed")]
    partial class CodeFirstDemoModelsEmployeeContextseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirstDemo.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DateOfBirth = new DateTime(1987, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "geetha@gmail.com",
                            FirstName = "Geetha",
                            LastName = "Samynathan",
                            Phonenumber = "950003433"
                        },
                        new
                        {
                            EmployeeId = 2,
                            DateOfBirth = new DateTime(1986, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tinaa@gmail.com",
                            FirstName = "tina",
                            LastName = "Sam",
                            Phonenumber = "999-444-6666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
